//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootprintViewer.Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootprintViewer.Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scene search.
        /// </summary>
        public static string FootprintPreviewTabTitle {
            get {
                return ResourceManager.GetString("FootprintPreviewTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Footprint viewer.
        /// </summary>
        public static string FootprintTabTitle {
            get {
                return ResourceManager.GetString("FootprintTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ground station viewer.
        /// </summary>
        public static string GroundStationTabTtile {
            get {
                return ResourceManager.GetString("GroundStationTabTtile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ground target viewer.
        /// </summary>
        public static string GroundTargetTabTitle {
            get {
                return ResourceManager.GetString("GroundTargetTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        public static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Satellite viewer.
        /// </summary>
        public static string SatelliteTabTitle {
            get {
                return ResourceManager.GetString("SatelliteTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Languages.
        /// </summary>
        public static string SettingsLanguages {
            get {
                return ResourceManager.GetString("SettingsLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data providers.
        /// </summary>
        public static string SettingsProviders {
            get {
                return ResourceManager.GetString("SettingsProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to finish drawing.
        /// </summary>
        public static string TipBeginCreatingCircle {
            get {
                return ResourceManager.GetString("TipBeginCreatingCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to continue drawing the shape.
        /// </summary>
        public static string TipBeginCreatingPolygon {
            get {
                return ResourceManager.GetString("TipBeginCreatingPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to finish drawing.
        /// </summary>
        public static string TipBeginCreatingRectangle {
            get {
                return ResourceManager.GetString("TipBeginCreatingRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click on the first point to close this shape.
        /// </summary>
        public static string TipCreatingPolygon {
            get {
                return ResourceManager.GetString("TipCreatingPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click and drag to draw a circle.
        /// </summary>
        public static string TipInitCircle {
            get {
                return ResourceManager.GetString("TipInitCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to draw a point.
        /// </summary>
        public static string TipInitPoint {
            get {
                return ResourceManager.GetString("TipInitPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click and drag to draw a polygon.
        /// </summary>
        public static string TipInitPolygon {
            get {
                return ResourceManager.GetString("TipInitPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click and drag to draw a rectangle.
        /// </summary>
        public static string TipInitRectangle {
            get {
                return ResourceManager.GetString("TipInitRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to start measurement.
        /// </summary>
        public static string TipInitRoute {
            get {
                return ResourceManager.GetString("TipInitRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User geometry.
        /// </summary>
        public static string UserGeometryTabTitle {
            get {
                return ResourceManager.GetString("UserGeometryTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User settings.
        /// </summary>
        public static string UserSettingsTabTitle {
            get {
                return ResourceManager.GetString("UserSettingsTabTitle", resourceCulture);
            }
        }
    }
}
