//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootprintViewer.Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootprintViewer.Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All satellites.
        /// </summary>
        public static string FilterAllSatellites {
            get {
                return ResourceManager.GetString("FilterAllSatellites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All sensors.
        /// </summary>
        public static string FilterAllSensors {
            get {
                return ResourceManager.GetString("FilterAllSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cloudiness.
        /// </summary>
        public static string FilterCloudiness {
            get {
                return ResourceManager.GetString("FilterCloudiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string FilterDate {
            get {
                return ResourceManager.GetString("FilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From node:.
        /// </summary>
        public static string FilterFromNode {
            get {
                return ResourceManager.GetString("FilterFromNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full cover AOI.
        /// </summary>
        public static string FilterFullCoverAOI {
            get {
                return ResourceManager.GetString("FilterFullCoverAOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter options.
        /// </summary>
        public static string FilterOptions {
            get {
                return ResourceManager.GetString("FilterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Satellites.
        /// </summary>
        public static string FilterSatellites {
            get {
                return ResourceManager.GetString("FilterSatellites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sensors.
        /// </summary>
        public static string FilterSensors {
            get {
                return ResourceManager.GetString("FilterSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sun elevation.
        /// </summary>
        public static string FilterSunElevation {
            get {
                return ResourceManager.GetString("FilterSunElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To node:.
        /// </summary>
        public static string FilterToNode {
            get {
                return ResourceManager.GetString("FilterToNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scene search.
        /// </summary>
        public static string FootprintPreviewTabTitle {
            get {
                return ResourceManager.GetString("FootprintPreviewTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Footprint viewer.
        /// </summary>
        public static string FootprintTabTitle {
            get {
                return ResourceManager.GetString("FootprintTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equal.
        /// </summary>
        public static string GroundStationModeEqual {
            get {
                return ResourceManager.GetString("GroundStationModeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Geometric.
        /// </summary>
        public static string GroundStationModeGeometric {
            get {
                return ResourceManager.GetString("GroundStationModeGeometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string GroundStationModeNone {
            get {
                return ResourceManager.GetString("GroundStationModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ground station viewer.
        /// </summary>
        public static string GroundStationTabTtile {
            get {
                return ResourceManager.GetString("GroundStationTabTtile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ground targets for this zoom level not access.
        /// </summary>
        public static string GroundTargetPreviewText {
            get {
                return ResourceManager.GetString("GroundTargetPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ground target viewer.
        /// </summary>
        public static string GroundTargetTabTitle {
            get {
                return ResourceManager.GetString("GroundTargetTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        public static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument of perigee.
        /// </summary>
        public static string SatelliteArgOfPerigee {
            get {
                return ResourceManager.GetString("SatelliteArgOfPerigee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eccentricity.
        /// </summary>
        public static string SatelliteEccentricity {
            get {
                return ResourceManager.GetString("SatelliteEccentricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Epoch.
        /// </summary>
        public static string SatelliteEpoch {
            get {
                return ResourceManager.GetString("SatelliteEpoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inclination.
        /// </summary>
        public static string SatelliteInclination {
            get {
                return ResourceManager.GetString("SatelliteInclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inner half angle.
        /// </summary>
        public static string SatelliteInnerHalfAngle {
            get {
                return ResourceManager.GetString("SatelliteInnerHalfAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left swath.
        /// </summary>
        public static string SatelliteLeftSwath {
            get {
                return ResourceManager.GetString("SatelliteLeftSwath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Longitude of the ascending node.
        /// </summary>
        public static string SatelliteLonAN {
            get {
                return ResourceManager.GetString("SatelliteLonAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outer half angle.
        /// </summary>
        public static string SatelliteOuterHalfAngle {
            get {
                return ResourceManager.GetString("SatelliteOuterHalfAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Period.
        /// </summary>
        public static string SatellitePeriod {
            get {
                return ResourceManager.GetString("SatellitePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RAAN.
        /// </summary>
        public static string SatelliteRAAN {
            get {
                return ResourceManager.GetString("SatelliteRAAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right swath.
        /// </summary>
        public static string SatelliteRightSwath {
            get {
                return ResourceManager.GetString("SatelliteRightSwath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Semiaxis.
        /// </summary>
        public static string SatelliteSemiaxis {
            get {
                return ResourceManager.GetString("SatelliteSemiaxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Satellite viewer.
        /// </summary>
        public static string SatelliteTabTitle {
            get {
                return ResourceManager.GetString("SatelliteTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Track.
        /// </summary>
        public static string SatelliteTrack {
            get {
                return ResourceManager.GetString("SatelliteTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Languages.
        /// </summary>
        public static string SettingsLanguages {
            get {
                return ResourceManager.GetString("SettingsLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data providers.
        /// </summary>
        public static string SettingsProviders {
            get {
                return ResourceManager.GetString("SettingsProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/Hide.
        /// </summary>
        public static string ShowHide {
            get {
                return ResourceManager.GetString("ShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to finish drawing.
        /// </summary>
        public static string TipBeginCreatingCircle {
            get {
                return ResourceManager.GetString("TipBeginCreatingCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to continue drawing the shape.
        /// </summary>
        public static string TipBeginCreatingPolygon {
            get {
                return ResourceManager.GetString("TipBeginCreatingPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to finish drawing.
        /// </summary>
        public static string TipBeginCreatingRectangle {
            get {
                return ResourceManager.GetString("TipBeginCreatingRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click on the first point to close this shape.
        /// </summary>
        public static string TipCreatingPolygon {
            get {
                return ResourceManager.GetString("TipCreatingPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click and drag to draw a circle.
        /// </summary>
        public static string TipInitCircle {
            get {
                return ResourceManager.GetString("TipInitCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to draw a point.
        /// </summary>
        public static string TipInitPoint {
            get {
                return ResourceManager.GetString("TipInitPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click and drag to draw a polygon.
        /// </summary>
        public static string TipInitPolygon {
            get {
                return ResourceManager.GetString("TipInitPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click and drag to draw a rectangle.
        /// </summary>
        public static string TipInitRectangle {
            get {
                return ResourceManager.GetString("TipInitRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to start measurement.
        /// </summary>
        public static string TipInitRoute {
            get {
                return ResourceManager.GetString("TipInitRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw circle AOI.
        /// </summary>
        public static string ToolBarAddCircle {
            get {
                return ResourceManager.GetString("ToolBarAddCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw polygon AOI.
        /// </summary>
        public static string ToolBarAddPolygon {
            get {
                return ResourceManager.GetString("ToolBarAddPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw rectangle AOI.
        /// </summary>
        public static string ToolBarAddRectangle {
            get {
                return ResourceManager.GetString("ToolBarAddRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw circle.
        /// </summary>
        public static string ToolBarCircle {
            get {
                return ResourceManager.GetString("ToolBarCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit geometry.
        /// </summary>
        public static string ToolBarEdit {
            get {
                return ResourceManager.GetString("ToolBarEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List map backgrounds.
        /// </summary>
        public static string ToolBarMapBackgrounds {
            get {
                return ResourceManager.GetString("ToolBarMapBackgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List map layers.
        /// </summary>
        public static string ToolBarMapLayers {
            get {
                return ResourceManager.GetString("ToolBarMapLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw point.
        /// </summary>
        public static string ToolBarPoint {
            get {
                return ResourceManager.GetString("ToolBarPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw polygon.
        /// </summary>
        public static string ToolBarPolygon {
            get {
                return ResourceManager.GetString("ToolBarPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw rectangle.
        /// </summary>
        public static string ToolBarRectangle {
            get {
                return ResourceManager.GetString("ToolBarRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rotate geometry.
        /// </summary>
        public static string ToolBarRotate {
            get {
                return ResourceManager.GetString("ToolBarRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measure route.
        /// </summary>
        public static string ToolBarRoute {
            get {
                return ResourceManager.GetString("ToolBarRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale geometry.
        /// </summary>
        public static string ToolBarScale {
            get {
                return ResourceManager.GetString("ToolBarScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select geometry.
        /// </summary>
        public static string ToolBarSelect {
            get {
                return ResourceManager.GetString("ToolBarSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translate geometry.
        /// </summary>
        public static string ToolBarTranslate {
            get {
                return ResourceManager.GetString("ToolBarTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom in.
        /// </summary>
        public static string ToolBarZoomIn {
            get {
                return ResourceManager.GetString("ToolBarZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom out.
        /// </summary>
        public static string ToolBarZoomOut {
            get {
                return ResourceManager.GetString("ToolBarZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User geometry.
        /// </summary>
        public static string UserGeometryTabTitle {
            get {
                return ResourceManager.GetString("UserGeometryTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User settings.
        /// </summary>
        public static string UserSettingsTabTitle {
            get {
                return ResourceManager.GetString("UserSettingsTabTitle", resourceCulture);
            }
        }
    }
}
